
package tienda2;
import ConexionBD.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import static java.lang.Character.isDigit;
import static java.lang.Character.isLetter;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

public class Agregarprod extends javax.swing.JDialog {
    
    Conexion conexion = new Conexion();
    boolean cod=false;
    boolean nomb=false;
    boolean prove=false;
    boolean marc=false;
    boolean comp=false;
    boolean vent=false;
    boolean precc=false;
    boolean cant=false;
    boolean precv=false;
    boolean unicaj=false;
    String proo="";
    
    String seleccion="";
    
    DefaultListModel mm = new DefaultListModel();
    

    /**
     * Creates new form Agregarprod
     */
    public Agregarprod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        labelcaja.setVisible(false);
        lineapieza.setVisible(false);
        unidadcaja.setVisible(false);
        pieza.setVisible(false);
        jPanel2.setVisible(false);
        //
        visible(false);
//        labelprecio.setVisible(false);
//        prec_comp.setVisible(false);
//        lineacompra.setVisible(false);
//        jLabel15.setVisible(false);
//        prec_vent.setVisible(false);
//        lineaventa.setVisible(false);
        
        //
        lista.setModel(mm);
        this.setLocationRelativeTo(null);
        jLabel1.setVisible(false);
       
    }
    boolean hay=false;
    
    public void buscarregistros(String str) {
        hay=false;
          mm.clear();
                                            
          ResultSet datos = conexion.consultas("select * from portillito.proveedor where razonsocial like "+"'"+str+"%"+"'");
        try {
            while (datos.next()) {
                String id = datos.getString("idproveedor");
                String nombre = datos.getString("razonsocial");

                mm.addElement(""+nombre);
                hay=true;
                
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lineacodigo = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lineanombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        lineamarca = new javax.swing.JLabel();
        prec_comp = new javax.swing.JTextField();
        lineacompra = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        unidadcaja = new javax.swing.JTextField();
        labelcaja = new javax.swing.JLabel();
        lineapieza = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        prec_vent = new javax.swing.JTextField();
        lineaventa = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        proveedor = new javax.swing.JTextField();
        lineaprov = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        labelprecio = new javax.swing.JLabel();
        pieza = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(735, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineacodigo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 11)); // NOI18N
        lineacodigo.setForeground(new java.awt.Color(153, 153, 153));
        lineacodigo.setText("______________________");
        jPanel1.add(lineacodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 96, 170, -1));

        codigo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        codigo.setForeground(new java.awt.Color(153, 153, 153));
        codigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigo.setText("Código");
        codigo.setBorder(null);
        codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoMouseClicked(evt);
            }
        });
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoFocusLost(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 86, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setText("Nombre del Producto");
        nombre.setBorder(null);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFocusLost(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 230, -1));

        lineanombre.setForeground(new java.awt.Color(153, 153, 153));
        lineanombre.setText("______________________________");
        jPanel1.add(lineanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Marca");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        marca.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        marca.setForeground(new java.awt.Color(153, 153, 153));
        marca.setText("Marca del Producto");
        marca.setBorder(null);
        marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marcaMouseClicked(evt);
            }
        });
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });
        marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                marcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                marcaFocusLost(evt);
            }
        });
        marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marcaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marcaKeyTyped(evt);
            }
        });
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, -1));

        lineamarca.setForeground(new java.awt.Color(153, 153, 153));
        lineamarca.setText("______________________________");
        jPanel1.add(lineamarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 20));

        prec_comp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        prec_comp.setForeground(new java.awt.Color(153, 153, 153));
        prec_comp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        prec_comp.setText("0.00");
        prec_comp.setBorder(null);
        prec_comp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prec_compMouseClicked(evt);
            }
        });
        prec_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec_compActionPerformed(evt);
            }
        });
        prec_comp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prec_compFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prec_compFocusLost(evt);
            }
        });
        prec_comp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prec_compKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prec_compKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prec_compKeyTyped(evt);
            }
        });
        jPanel1.add(prec_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 66, -1));

        lineacompra.setForeground(new java.awt.Color(153, 153, 153));
        lineacompra.setText("___________");
        jPanel1.add(lineacompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 79, -1));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/boton.png"))); // NOI18N
        aceptar.setBorderPainted(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setEnabled(false);
        aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/boton2.png"))); // NOI18N
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 100, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/cancelar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/cancelar2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 100, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opción", "Caja", "Paquete", "Charola", "Bulto", "Unitario" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Código");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Presentacion del Producto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        unidadcaja.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        unidadcaja.setForeground(new java.awt.Color(153, 153, 153));
        unidadcaja.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unidadcaja.setText("0");
        unidadcaja.setBorder(null);
        unidadcaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidadcajaMouseClicked(evt);
            }
        });
        unidadcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadcajaActionPerformed(evt);
            }
        });
        unidadcaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unidadcajaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unidadcajaFocusLost(evt);
            }
        });
        unidadcaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unidadcajaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadcajaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unidadcajaKeyTyped(evt);
            }
        });
        jPanel1.add(unidadcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 40, -1));

        labelcaja.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelcaja.setForeground(new java.awt.Color(102, 102, 102));
        labelcaja.setText("Numero de Unidades Por Caja");
        jPanel1.add(labelcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        lineapieza.setForeground(new java.awt.Color(153, 153, 153));
        lineapieza.setText("_______");
        jPanel1.add(lineapieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Precio de Venta por Unidad");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        prec_vent.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        prec_vent.setForeground(new java.awt.Color(153, 153, 153));
        prec_vent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        prec_vent.setText("0.00");
        prec_vent.setBorder(null);
        prec_vent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prec_ventMouseClicked(evt);
            }
        });
        prec_vent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec_ventActionPerformed(evt);
            }
        });
        prec_vent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prec_ventFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prec_ventFocusLost(evt);
            }
        });
        prec_vent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prec_ventKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prec_ventKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prec_ventKeyTyped(evt);
            }
        });
        jPanel1.add(prec_vent, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 70, -1));

        lineaventa.setForeground(new java.awt.Color(153, 153, 153));
        lineaventa.setText("___________");
        jPanel1.add(lineaventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 79, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Proveedor");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        proveedor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        proveedor.setForeground(new java.awt.Color(153, 153, 153));
        proveedor.setText("Nombre del Proveedor");
        proveedor.setBorder(null);
        proveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proveedorFocusLost(evt);
            }
        });
        proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedorMouseClicked(evt);
            }
        });
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });
        proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                proveedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                proveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                proveedorKeyTyped(evt);
            }
        });
        jPanel1.add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 200, -1));

        lineaprov.setForeground(new java.awt.Color(153, 153, 153));
        lineaprov.setText("______________________________");
        jPanel1.add(lineaprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 220, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setBorder(null);
        lista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lista.setForeground(new java.awt.Color(153, 153, 153));
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 250, 160));

        labelprecio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelprecio.setForeground(new java.awt.Color(102, 102, 102));
        labelprecio.setText("Precio de compra");
        jPanel1.add(labelprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        pieza.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pieza.setForeground(new java.awt.Color(153, 153, 153));
        pieza.setText("piezas");
        jPanel1.add(pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        p2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(153, 153, 153));
        p2.setText("$");
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        p1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(153, 153, 153));
        p1.setText("$");
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Agregar Proveedor");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoFocusLost
        // TODO add your handling code here:
        
        if(codigo.getText().equals("")){
            codigo.setText("Código");
            lineacodigo.setForeground(f);codigo.setForeground(f);
            cod=false;
        }
    }//GEN-LAST:event_codigoFocusLost

    private void codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoMouseClicked
        // TODO add your handling code here:
        //if(!cod) codigo.setText("");
    }//GEN-LAST:event_codigoMouseClicked

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed
    
    }//GEN-LAST:event_codigoKeyPressed

    private void nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusLost
        // TODO add your handling code here:
       
        if(nombre.getText().equals("")){
            nombre.setText("Nombre del Producto");
            lineanombre.setForeground(f);nombre.setForeground(f);
            nomb=false;
        }
    }//GEN-LAST:event_nombreFocusLost

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        // TODO add your handling code here:
        if(!nomb) nombre.setText("");
    }//GEN-LAST:event_nombreMouseClicked

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed

    }//GEN-LAST:event_nombreKeyPressed

    private void marcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcaFocusLost
        // TODO add your handling code here:
       
        if(marca.getText().equals("")){
            marca.setText("Marca del Producto");
            lineamarca.setForeground(f);marca.setForeground(f);
            marc=false;
        }
    }//GEN-LAST:event_marcaFocusLost

    private void marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaMouseClicked
        // TODO add your handling code here:
        if(!marc) marca.setText("");
    }//GEN-LAST:event_marcaMouseClicked

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    private void marcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_marcaKeyPressed

    private void prec_compFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prec_compFocusLost
        // TODO add your handling code here:
      
        if(prec_comp.getText().equals("")){
            prec_comp.setText("0.00");
            lineacompra.setForeground(f);prec_comp.setForeground(f);
        }
    }//GEN-LAST:event_prec_compFocusLost

    private void prec_compMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prec_compMouseClicked
     
    }//GEN-LAST:event_prec_compMouseClicked

    private void prec_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prec_compActionPerformed

    private void prec_compKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prec_compKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_prec_compKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String present = seleccion=jComboBox1.getSelectedItem().toString();
        String unicajj = unidadcaja.getText();
        if(present.equals("Unitario"))
            unicajj="1";
        
        String cad = codigo.getText()+",'"+nombre.getText()+"','"+marca.getText()+"',"+prec_comp.getText()+","+prec_vent.getText()+",0";    
        conexion.consultas("insert into portillito.producto values("+cad+")");
        String cad2=codigo.getText()+",'"+present+"',"+unidadcaja.getText();
        conexion.consultas("insert into portillito.presentacion_p values("+cad2+")");

        ResultSet res = conexion.consultas("select * from portillito.proveedor where razonsocial = '"+proveedor.getText()+"'");
        
        try {
            while (res.next()) {
                String id = res.getString("idproveedor");
                conexion.consultas("insert into portillito.catalogo_prod_prov values("+codigo.getText()+","+id+")");
            }
        } catch (Exception e) {
        }
        
        Correcto c;
        Error e;
        if(conexion.getConsulta()){
             c= new Correcto(new javax.swing.JFrame(),true);
             c.setVisible(true);
             this.dispose();
        }
        else{
            e=new Error(new javax.swing.JFrame(),true,"Producto no agregado");
            e.setVisible(true);
        }
         
    }//GEN-LAST:event_aceptarActionPerformed

    private void codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoFocusGained
        // TODO add your handling code here:
        if(!cod) codigo.setText("");
    }//GEN-LAST:event_codigoFocusGained

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        seleccion=jComboBox1.getSelectedItem().toString();
        visible(true);
        switch(seleccion){
            case "Caja":
                pieza.setText("Piezas");
                pieza.setVisible(true);
                labelcaja.setText("Numero de Unidades Por caja");
                labelcaja.setVisible(true);
                lineapieza.setVisible(true);
                unidadcaja.setVisible(true);  
                 labelprecio.setText("Precio de compra por caja");
            break;
            case "Charola":
                pieza.setText("Piezas");
                pieza.setVisible(true);
                labelcaja.setText("Numero de Unidades Por Charola");
                labelcaja.setVisible(true);
                lineapieza.setVisible(true);
                unidadcaja.setVisible(true);  
                labelprecio.setText("Precio de compra por Charola");
                break;
            case "Paquete":
                pieza.setText("Piezas");
                pieza.setVisible(true);
                labelcaja.setText("Numero de Unidades Por Paquete");
                labelcaja.setVisible(true);
                lineapieza.setVisible(true);
                unidadcaja.setVisible(true);  
                labelprecio.setText("Precio de compra por Paquete");
                break;
            case "Bulto":
                pieza.setText("Kgs");
                pieza.setVisible(true);
                labelcaja.setText("Numero de kg por Bultos");
                labelcaja.setVisible(true);
                lineapieza.setVisible(true);
                unidadcaja.setVisible(true);  
                labelprecio.setText("Precio de compra por Bulto");
                break;
            case "Unitario":
                pieza.setVisible(false);
                labelprecio.setText("Precio de compra");
                labelcaja.setVisible(false);
                lineapieza.setVisible(false);
                unidadcaja.setVisible(false);
                break;
            case "Seleccione una Opción":
                visible(false);
                break;
                
        }
        /*Paquete
Charola
Bulto
Unitario*/

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void unidadcajaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unidadcajaFocusLost
        // TODO add your handling code here:
      
        if(unidadcaja.getText().equals("")){
            unidadcaja.setText("0");
            lineapieza.setForeground(f);unidadcaja.setForeground(f);
            unicaj=false;
        }
    }//GEN-LAST:event_unidadcajaFocusLost

    private void unidadcajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidadcajaMouseClicked
        // TODO add your handling code here:
        if(!unicaj) unidadcaja.setText("");
    }//GEN-LAST:event_unidadcajaMouseClicked

    private void unidadcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadcajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadcajaActionPerformed

    private void unidadcajaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadcajaKeyPressed
        // TODO add your handling code here:
        unicaj=true;
    }//GEN-LAST:event_unidadcajaKeyPressed

    private void prec_ventFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prec_ventFocusLost
        // TODO add your handling code here:
        if(prec_vent.getText().equals("")){
            prec_vent.setText("0.00");
           lineaventa.setForeground(f);prec_vent.setForeground(f);
        }
    }//GEN-LAST:event_prec_ventFocusLost

    private void prec_ventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prec_ventMouseClicked
        // TODO add your handling code here:
        if(!precv) prec_vent.setText("");
    }//GEN-LAST:event_prec_ventMouseClicked

    private void prec_ventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec_ventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prec_ventActionPerformed

    private void prec_ventKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prec_ventKeyPressed

    }//GEN-LAST:event_prec_ventKeyPressed

    private void proveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proveedorFocusLost
        // TODO add your handling code here:
       // if(!precv) proveedor.setText("Nombre del Proveedor");
        if(proveedor.getText().equals("")){
            proveedor.setText("Nombre del Proveedor");
          //  precv=false;
            lineaprov.setForeground(f);proveedor.setForeground(f);
            jPanel2.setVisible(false);
        }
    }//GEN-LAST:event_proveedorFocusLost

    private void proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseClicked
        // TODO add your handling code here:
//        if(!precv) proveedor.setText("");
    }//GEN-LAST:event_proveedorMouseClicked

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorActionPerformed

    private void proveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proveedorKeyPressed

    }//GEN-LAST:event_proveedorKeyPressed

    private void proveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proveedorKeyReleased
        if(evt.getKeyCode()!=8){
        jPanel2.setVisible(true);
        buscarregistros(proveedor.getText());
       }
        if(!hay){ 
            proveedor.setForeground(f);
            lineaprov.setForeground(f);
            jLabel1.setVisible(true);
            
        }
        else jLabel1.setVisible(false);
        
    }//GEN-LAST:event_proveedorKeyReleased

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:
        System.out.println(lista.getSelectedIndex());
    }//GEN-LAST:event_listaMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyReleased

    }//GEN-LAST:event_codigoKeyReleased

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        // TODO add your handling code here:
         if(codigo.getText().length()>17 || !isDigit(evt.getKeyChar()))evt.consume();
         if(codigo.getText().length()>3){lineacodigo.setForeground(t);codigo.setForeground(l);cod=true;}
         else {lineacodigo.setForeground(f);codigo.setForeground(f);cod=false;}
         validar();
    }//GEN-LAST:event_codigoKeyTyped
    public void validar() {
        if (cod && nomb && prove && marc && comp && vent) {
            aceptar.setEnabled(true);
        } else {
            aceptar.setEnabled(false);
        }
    }

    ;
    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
        
        if(nombre.getText().length()>25)evt.consume();
        if(nombre.getText().length()>2) {lineanombre.setForeground(t);nombre.setForeground(l);nomb=true;}
        else {lineanombre.setForeground(f);nombre.setForeground(f);nomb=false;}
        validar();
    }//GEN-LAST:event_nombreKeyTyped

    private void marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaKeyTyped
        // TODO add your handling code here:
        if(marca.getText().length()>25)evt.consume();
        if(marca.getText().length()>2){lineamarca.setForeground(t);marca.setForeground(l);marc=true;}
        else{lineamarca.setForeground(f);marca.setForeground(f);marc=false;}
        validar();
    }//GEN-LAST:event_marcaKeyTyped

    private void prec_compKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prec_compKeyTyped
        // TODO add your handling code here:

        if(prec_comp.getText().indexOf('.')!=-1 && evt.getKeyChar()=='.') evt.consume();        
        if(evt.getKeyChar()!='.' && !isDigit(evt.getKeyChar())|| prec_comp.getText().length()>7 )evt.consume();
        validar();
    }//GEN-LAST:event_prec_compKeyTyped

    private void prec_compKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prec_compKeyReleased
             // TODO add your handling code here:
        double n=0;
        try{
         n=Double.parseDouble(prec_comp.getText());}
        catch(Exception e){}
         if(n==0) {lineacompra.setForeground(f);prec_comp.setForeground(f);comp=false;}
         else {lineacompra.setForeground(t);prec_comp.setForeground(l);comp=true;}
         validar();
    }//GEN-LAST:event_prec_compKeyReleased

    private void prec_ventKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prec_ventKeyTyped
        // TODO add your handling code here:
        if(prec_vent.getText().indexOf('.')!=-1 && evt.getKeyChar()=='.') evt.consume();        
        if(evt.getKeyChar()!='.' && !isDigit(evt.getKeyChar())|| prec_vent.getText().length()>7 )evt.consume();
        validar();
    }//GEN-LAST:event_prec_ventKeyTyped

    private void prec_ventKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prec_ventKeyReleased
     double n=0;
        try{
         n=Double.parseDouble(prec_vent.getText());}
        catch(Exception e){}
         if(n==0) {lineaventa.setForeground(f);prec_vent.setForeground(f);vent=false;}
         else {lineaventa.setForeground(t);prec_vent.setForeground(l);vent=true;}
         validar();
    }//GEN-LAST:event_prec_ventKeyReleased

    private void unidadcajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadcajaKeyTyped
    if(!isDigit(evt.getKeyChar()) || unidadcaja.getText().length()>3) evt.consume();    
        
// TODO add your handling code here:
    }//GEN-LAST:event_unidadcajaKeyTyped

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        // TODO add your handling code here:
        seleccion=lista.getSelectedValue();
        if(seleccion!=null){
            proveedor.setText(seleccion);
            proveedor.setForeground(l);
            lineaprov.setForeground(t);
            jPanel2.setVisible(false);
            System.out.println(seleccion);
            prove = true;
        }
    
        
        

        //lista.clearSelection();
        validar();
    }//GEN-LAST:event_listaValueChanged

    private void proveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proveedorFocusGained
       lista.clearSelection();mm.clear();
        if(proveedor.getText().equals("Nombre del Proveedor"))
        proveedor.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorFocusGained

    private void nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusGained
        // TODO add your handling code here:
        //
        if(nombre.getText().equals("Nombre del Producto"))
           nombre.setText(""); 
       
    }//GEN-LAST:event_nombreFocusGained

    private void marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcaFocusGained
        // TODO add your handling code here:
        if(marca.getText().equals("Marca del Producto"))
        marca.setText("");
    }//GEN-LAST:event_marcaFocusGained

    private void prec_compFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prec_compFocusGained
        // TODO add your handling code here:
        if(prec_comp.getText().equals("0.00"))
           prec_comp.setText("");
    }//GEN-LAST:event_prec_compFocusGained

    private void unidadcajaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unidadcajaFocusGained
        // TODO add your handling code here:
        if(unidadcaja.getText().equals("0"))
        unidadcaja.setText("");
    }//GEN-LAST:event_unidadcajaFocusGained

    private void prec_ventFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prec_ventFocusGained
        // TODO add your handling code here:
        if(prec_vent.getText().equals("0.00"))
        prec_vent.setText("");
    }//GEN-LAST:event_prec_ventFocusGained

    private void proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proveedorKeyTyped
       
       
    }//GEN-LAST:event_proveedorKeyTyped

    private void unidadcajaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadcajaKeyReleased
        // TODO add your handling code here:
        double n=0;
        try{
         n=Double.parseDouble(unidadcaja.getText());}
        catch(Exception e){}
         if(n==0) {lineapieza.setForeground(f);unidadcaja.setForeground(f);}
         else {lineapieza.setForeground(t);unidadcaja.setForeground(l);}
    }//GEN-LAST:event_unidadcajaKeyReleased

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        AgregarProveedor ag = new AgregarProveedor(new javax.swing.JFrame(), true);
        ag.setVisible(true);
        buscarregistros(proveedor.getText());
        if(hay){ 
            proveedor.setForeground(l);
            lineaprov.setForeground(t);
            jLabel1.setVisible(false);
            prove=true;            
        }
        else {
            jLabel1.setVisible(true);
            prove=false;
        }
        
        validar();
    }//GEN-LAST:event_jLabel1MouseClicked
   public boolean boleanprov(String s){
    for(int x=0;x<mm.getSize();x++){
        if(s.equalsIgnoreCase((String)mm.get(x))){return true;}}
        
    return false;
    
   }
    public void visible(boolean b){
      labelprecio.setVisible(b);
        prec_comp.setVisible(b);
        lineacompra.setVisible(b);
        jLabel15.setVisible(b);
        prec_vent.setVisible(b);
        lineaventa.setVisible(b);
        p1.setVisible(b);
        p2.setVisible(b);
        labelcaja.setVisible(b);
        unidadcaja.setVisible(b);
        pieza.setVisible(b);
        lineapieza.setVisible(b);
    }
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregarprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregarprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregarprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregarprod dialog = new Agregarprod(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcaja;
    private javax.swing.JLabel labelprecio;
    private javax.swing.JLabel lineacodigo;
    private javax.swing.JLabel lineacompra;
    private javax.swing.JLabel lineamarca;
    private javax.swing.JLabel lineanombre;
    private javax.swing.JLabel lineapieza;
    private javax.swing.JLabel lineaprov;
    private javax.swing.JLabel lineaventa;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel pieza;
    private javax.swing.JTextField prec_comp;
    private javax.swing.JTextField prec_vent;
    private javax.swing.JTextField proveedor;
    private javax.swing.JTextField unidadcaja;
    // End of variables declaration//GEN-END:variables
 
 Color t= new Color(116,219,239);
 Color f=new Color(246,84,84);
 Color l=new Color(2,117,216);
}
