/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda2;

import ConexionBD.Conexion;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Luis Eduardo
 */
public class Recarga extends javax.swing.JDialog {

    /**
     * Creates new form Cliente
     */
    Conexion conexion= new Conexion();
     DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
     boolean foliob=false;
     boolean telb=false;
        Calendar cal=Calendar.getInstance();
        Date sistFecha=new Date();
        
        SimpleDateFormat formato=new SimpleDateFormat("dd-MMM-YYYY");
        
    public Recarga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tabla.setBackground(Color.WHITE);
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 1; i < 5; i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(alinear);
        }
        tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        tabla.getColumnModel().getColumn(0).setMinWidth(0);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        llenarTabla();
        
        
    }
    public void llenarTabla(){
        for (int i = 0; i < tabla.getRowCount(); i++) {
            DefaultTableModel mm = (DefaultTableModel) tabla.getModel();
            mm.removeRow(i);
            i -= 1;
        }
          ResultSet datos = conexion.consultas("select * from portillito.detalle_vrecarga");
        try {
            while (datos.next()) {
                String id = datos.getString("idventarecaga");
                String comp = datos.getString("compañia");
                String telf = datos.getString("numtelefono");
                String monto = datos.getString("monto");

                DefaultTableModel mm = (DefaultTableModel) tabla.getModel();
                mm.addRow(new Object[]{false, id, comp, telf,monto });
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        monto = new javax.swing.JComboBox();
        compania = new javax.swing.JComboBox();
        lineafolio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        folio = new javax.swing.JTextField();
        lineatelefono = new javax.swing.JLabel();
        telef = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        recarga1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        venta1 = new javax.swing.JButton();
        prod1 = new javax.swing.JButton();
        prov1 = new javax.swing.JButton();
        cliente1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1150, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/linea.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(966, 1));
        jLabel3.setMinimumSize(new java.awt.Dimension(966, 21));
        jLabel3.setPreferredSize(new java.awt.Dimension(966, 1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 970, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Folio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Compañia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Número Teléfonico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Monto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, -1, -1));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/agregar.png"))); // NOI18N
        aceptar.setBorderPainted(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.setEnabled(false);
        aceptar.setFocusable(false);
        aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subagregar.png"))); // NOI18N
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 100, 40));

        buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(204, 204, 204));
        buscar.setText("Ingrese Folio o número");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 210, -1));

        monto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "50", "100", "500" }));
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        jPanel1.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 100, -1));

        compania.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        compania.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telcel", "Movistar", "Unefon", "Iusacel", "Nextel" }));
        compania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiaActionPerformed(evt);
            }
        });
        jPanel1.add(compania, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 100, -1));

        lineafolio.setForeground(new java.awt.Color(153, 153, 153));
        lineafolio.setText("___________________");
        jPanel1.add(lineafolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Folio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        folio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        folio.setForeground(new java.awt.Color(153, 153, 153));
        folio.setText("Folio");
        folio.setBorder(null);
        folio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                folioMouseClicked(evt);
            }
        });
        folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioActionPerformed(evt);
            }
        });
        folio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                folioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                folioFocusLost(evt);
            }
        });
        folio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                folioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                folioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                folioKeyTyped(evt);
            }
        });
        jPanel1.add(folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, -1));

        lineatelefono.setForeground(new java.awt.Color(153, 153, 153));
        lineatelefono.setText("__________________");
        jPanel1.add(lineatelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        telef.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        telef.setForeground(new java.awt.Color(153, 153, 153));
        telef.setText("000-000-0000");
        telef.setBorder(null);
        telef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefMouseClicked(evt);
            }
        });
        telef.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefFocusLost(evt);
            }
        });
        telef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefKeyTyped(evt);
            }
        });
        jPanel1.add(telef, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Teléfono");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jPanel3.setBackground(new java.awt.Color(64, 75, 105));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recarga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/recarga.png"))); // NOI18N
        recarga1.setToolTipText("Recargas");
        recarga1.setBorder(null);
        recarga1.setBorderPainted(false);
        recarga1.setContentAreaFilled(false);
        recarga1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recarga1.setFocusPainted(false);
        recarga1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subrecarga.png"))); // NOI18N
        jPanel3.add(recarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 50, 42));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/011-home.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/home2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 42));

        venta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/006-coin.png"))); // NOI18N
        venta1.setToolTipText("Venta");
        venta1.setBorder(null);
        venta1.setBorderPainted(false);
        venta1.setContentAreaFilled(false);
        venta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        venta1.setFocusPainted(false);
        venta1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subventa.png"))); // NOI18N
        venta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venta1ActionPerformed(evt);
            }
        });
        jPanel3.add(venta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, 42));

        prod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/008-menu.png"))); // NOI18N
        prod1.setToolTipText("Productos");
        prod1.setBorder(null);
        prod1.setBorderPainted(false);
        prod1.setContentAreaFilled(false);
        prod1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prod1.setFocusPainted(false);
        prod1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subprod.png"))); // NOI18N
        prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod1ActionPerformed(evt);
            }
        });
        jPanel3.add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 42));

        prov1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/005-magic.png"))); // NOI18N
        prov1.setToolTipText("Proveedores");
        prov1.setBorder(null);
        prov1.setBorderPainted(false);
        prov1.setContentAreaFilled(false);
        prov1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prov1.setFocusPainted(false);
        prov1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subprov.png"))); // NOI18N
        prov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prov1ActionPerformed(evt);
            }
        });
        jPanel3.add(prov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 42));

        cliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/004-multiple-users-silhouette.png"))); // NOI18N
        cliente1.setToolTipText("Clientes");
        cliente1.setBorder(null);
        cliente1.setBorderPainted(false);
        cliente1.setContentAreaFilled(false);
        cliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cliente1.setFocusPainted(false);
        cliente1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subcliente.png"))); // NOI18N
        cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente1ActionPerformed(evt);
            }
        });
        jPanel3.add(cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 50, 42));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        tabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Folio", "compañia", "numero", "monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.setRowHeight(20);
        tabla.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tabla.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tabla.setTableHeader(null);
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 960, 400));

        jPanel4.setBackground(new java.awt.Color(231, 239, 243));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel4MouseMoved(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Nombre de usuario");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Registro de recargas");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/user.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, -1, -1));

        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(102, 102, 102));
        jButton11.setText("Cerrar sesión");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 120, 20));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Portillo |");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente1ActionPerformed

        this.dispose();
        Cliente c= new Cliente(new javax.swing.JFrame(),true);
        c.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente1ActionPerformed

    private void prov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prov1ActionPerformed
        this.dispose();
        Proveedor p= new Proveedor(new javax.swing.JFrame(),true);
        p.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_prov1ActionPerformed

    private void prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Producto p= new Producto(new javax.swing.JFrame(),true);
        p.setVisible(true);
    }//GEN-LAST:event_prod1ActionPerformed

    private void venta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venta1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        venta v= new venta(new javax.swing.JFrame(),true);
        v.setVisible(true);
    }//GEN-LAST:event_venta1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Principal p = new Principal(new javax.swing.JFrame(),true);
        p.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void telefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefKeyTyped
        // TODO add your handling code here:
        if(!isDigit(evt.getKeyChar())|| telef.getText().length()>11)evt.consume();
    }//GEN-LAST:event_telefKeyTyped

    private void telefKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefKeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()!=8){
            if(telef.getText().length()==3) telef.setText(telef.getText()+"-");
            if(telef.getText().length()==7) telef.setText(telef.getText()+"-");}
        if(telef.getText().length()>11){telef.setForeground(l);lineatelefono.setForeground(t);telb=true;}
        else{ telef.setForeground(f);lineatelefono.setForeground(f);telb=false;}

        validar();
    }//GEN-LAST:event_telefKeyReleased

    private void telefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_telefKeyPressed

    private void telefFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefFocusLost
        // TODO add your handling code here:

        if(telef.getText().equals(""))
        telef.setText("000-000-0000");

    }//GEN-LAST:event_telefFocusLost

    private void telefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefFocusGained
        // TODO add your handling code here:
        if(telef.getText().equals("000-000-0000"))telef.setText("");
    }//GEN-LAST:event_telefFocusGained

    private void telefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefMouseClicked
        // TODO add your handling code here:
        if(telef.getText().equals("000-000-0000"))
        telef.setText("");
    }//GEN-LAST:event_telefMouseClicked

    private void folioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9' || folio.getText().length()>11) evt.consume();

    }//GEN-LAST:event_folioKeyTyped

    private void folioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folioKeyReleased
        // TODO add your handling code here:
        if(folio.getText().length()>6){lineafolio.setForeground(t);folio.setForeground(l);foliob=true;}
        else {lineafolio.setForeground(f);folio.setForeground(f);foliob=false;}
        validar();
    }//GEN-LAST:event_folioKeyReleased

    private void folioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folioKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_folioKeyPressed

    private void folioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_folioFocusLost
        // TODO add your handling code here:

        if(folio.getText().equals(""))
        folio.setText("Folio");

    }//GEN-LAST:event_folioFocusLost

    private void folioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_folioFocusGained
        // TODO add your handling code here:
        if(folio.getText().equals("Folio"))folio.setText("");
    }//GEN-LAST:event_folioFocusGained

    private void folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folioActionPerformed

    private void folioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_folioMouseClicked
        // TODO add your handling code here:
        if(folio.getText().equals("Folio")) folio.setText("");
    }//GEN-LAST:event_folioMouseClicked

    private void companiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companiaActionPerformed

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        if(evt.getKeyChar()==10) buscar.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyReleased

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        if(buscar.getText().equals("Ingrese Folio o número")){
            buscar.setText("");
            buscar.setForeground(Color.BLACK);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMouseClicked

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed

        Date sistHora = new Date();
        String pm="hh:mm:ss";
        SimpleDateFormat format=new SimpleDateFormat(pm);
        Calendar hoy=Calendar.getInstance();
        String s=formato.format(sistFecha);
        String d=String.format(format.format(sistHora), hoy);
        //3596002;"2018-03-01";"12:00:00"
        String cad2=folio.getText()+",'"+s+"','"+d+"'";

        String cad =folio.getText()+",'"+compania.getSelectedItem()+"','"+telef.getText()+"',"+monto.getSelectedItem();
        conexion.consultas("insert into portillito.ventarecarga values("+cad2+")");
        conexion.consultas("insert into portillito.detalle_vrecarga values("+cad+")");
        Correcto c;
        Error e;
        if(conexion.getConsulta()){
            c=new Correcto(new javax.swing.JFrame(), true);
            c.setVisible(true);
        }
        else{
            e=new Error(new javax.swing.JFrame(), true,"Recarga no agregada");
            e.setVisible(true);
        }

        llenarTabla();
        System.out.println(s+"----"+d);

    }//GEN-LAST:event_aceptarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          AdvertenciaC c= new AdvertenciaC(new javax.swing.JFrame(), true,this);
        c.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseMoved
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel4MouseMoved
public void validar(){
  if(telb && foliob)aceptar.setEnabled(true);
  else aceptar.setEnabled(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Recarga dialog = new Recarga(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton cliente1;
    private javax.swing.JComboBox compania;
    private javax.swing.JTextField folio;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lineafolio;
    private javax.swing.JLabel lineatelefono;
    private javax.swing.JComboBox monto;
    private javax.swing.JButton prod1;
    private javax.swing.JButton prov1;
    private javax.swing.JButton recarga1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telef;
    private javax.swing.JButton venta1;
    // End of variables declaration//GEN-END:variables
boolean bandera=false;
 Color t= new Color(116,219,239);
 Color f=new Color(246,84,84);
 Color l=new Color(2,117,216);
 int x,y;
}
