/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda2;

import ConexionBD.Conexion;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Eduardo
 */
public class venta extends javax.swing.JDialog {

    /**
     * Creates new form Producto
     */
    Conexion con= new Conexion();
    DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
    boolean activar=true;
    ArrayList<String> codigos= new ArrayList<String>();
    ArrayList<String> precios= new ArrayList<String>();
   float total=0;
    public venta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tabla.setBackground(Color.white);
        precio.setBorder(null);
        this.setLocationRelativeTo(null);
         tabla.setBackground(Color.WHITE);
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 1; i < 5; i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(alinear);
        }
        tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        tabla.getColumnModel().getColumn(0).setMinWidth(0);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        usuario.setText(usu());
    }
public String usu(){
        ResultSet datos = con.consultas("select * from portillito.usuarioactivo");
        String nombre="";
        try {
            while(datos.next()){
                nombre=datos.getString("nombre");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nombre;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        importe = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        cod = new javax.swing.JLabel();
        prod = new javax.swing.JLabel();
        prec = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cambio = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        marc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto");
        setMinimumSize(new java.awt.Dimension(1150, 700));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(64, 75, 105));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/003-phone-call.png"))); // NOI18N
        jButton1.setToolTipText("Recargas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subrecarga.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 50, 42));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/011-home.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/home2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 42));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/venta.png"))); // NOI18N
        jButton3.setToolTipText("Venta");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subventa.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, 42));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/008-menu.png"))); // NOI18N
        jButton4.setToolTipText("Productos");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subprod.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 42));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/005-magic.png"))); // NOI18N
        jButton5.setToolTipText("Proveedores");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subprov.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 42));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/004-multiple-users-silhouette.png"))); // NOI18N
        jButton6.setToolTipText("Cliente");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subcliente.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 50, 42));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/linea.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(966, 1));
        jLabel3.setMinimumSize(new java.awt.Dimension(966, 21));
        jLabel3.setPreferredSize(new java.awt.Dimension(966, 1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 900, 10));

        importe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        importe.setText("Importe");
        jPanel1.add(importe, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/cancelar.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/cancelar2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 100, 40));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/aceptar.png"))); // NOI18N
        aceptar.setBorderPainted(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.setEnabled(false);
        aceptar.setFocusable(false);
        aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subaceptar.png"))); // NOI18N
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 100, 40));

        buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(204, 204, 204));
        buscar.setText("Escanea o inserta código");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscarFocusLost(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, -1));

        cod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cod.setText("Código");
        jPanel1.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        prod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prod.setText("Producto");
        jPanel1.add(prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        prec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prec.setText("Precio");
        jPanel1.add(prec, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad.setText("Cantidad");
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tabla.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "codigo", "producto", "marca", "Precio ", "cantidad", "importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setRowHeight(25);
        tabla.setSelectionBackground(new java.awt.Color(199, 199, 255));
        tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabla.setTableHeader(null);
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 900, 260));

        cambio.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cambio.setText("Cambio:$");
        jPanel1.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        precio.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioKeyTyped(evt);
            }
        });
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 100, -1));

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 120, 20));

        tot.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tot.setText("Total  :$");
        jPanel1.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Recibo:$");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/eliminar.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusable(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/subeliminar.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 100, 40));

        marc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        marc.setText("Marca");
        jPanel1.add(marc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jPanel3.setBackground(new java.awt.Color(231, 239, 243));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(102, 102, 102));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("Nombre");
        jPanel3.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 80, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Cobro de productos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda2/imagenes/user.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, -1, -1));

        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(102, 102, 102));
        jButton11.setText("Cerrar sesión");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 120, 20));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Portillo |");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Principal p = new Principal(new javax.swing.JFrame(),true);
        p.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de cancelar la venta?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
       // System.out.println(resp);
        if(resp==0)
        {
           DefaultTableModel mm = (DefaultTableModel) tabla.getModel();
           System.out.print(mm.getRowCount());
            for(int x=0;x<tabla.getRowCount();x++)
            mm.removeRow(x); 
            tot.setText("Total :$");
            total=0;
            codigos.clear();
            precios.clear();
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        boolean b=false;
        Error e;
        Correcto c;
        if (b){
         c=new Correcto(new javax.swing.JFrame(),true);
         c.setVisible(true);
        }
        else 
        {
         e = new Error(new javax.swing.JFrame(),true,"Venta no realizada");
         e.setVisible(true);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscarMouseClicked

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
      //System.out.print(evt.getKeyCode());
      
      if(evt.getKeyCode()==10){buscar(buscar.getText());buscar.setText("");}
    }//GEN-LAST:event_buscarKeyReleased
   public void buscar(String s){
      ResultSet datos = con.consultas("select * from portillito.producto where codigo="+s);
      DefaultTableModel mm = (DefaultTableModel) tabla.getModel();
      
      boolean bol=false;
         try {
            while (datos.next()) {
                bol=true;
                String id = datos.getString("codigo");
                String nombre = datos.getString("nombre");
                String marca = datos.getString("marca");
                String precio= datos.getString("precioventa");
                float preciov=Float.parseFloat(precio);
               
                if(!serepite(id))
                    {codigos.add(id);
                    precios.add(""+preciov);
                    mm = (DefaultTableModel) tabla.getModel();
                    mm.addRow(new Object[]{false, id, nombre,marca,precio,1,preciov});
                    
                    }
                else{
                    
                    mm = (DefaultTableModel) tabla.getModel();
                    
                   for(int x=0;x<mm.getRowCount();x++){                       
                    System.out.println("entro");
                     if(id.equals(mm.getValueAt(x, 1)))
                     {
                         float n=(int)mm.getValueAt(x, 5)+1;
                         float p=Float.parseFloat(precios.get(x))*n;
                      
                         int n1=(int)n;
                         mm.setValueAt(n1, x, 5);
                         mm.setValueAt(p, x, 6);
                         System.out.println(mm.getValueAt(x, 1));
                         break;
                     }
                   }
                }
               
            }
        } catch (Exception e) { System.out.println(e);
        }
       if(!bol && !buscar.getText().equals("")){
          Busqueda b= new Busqueda(new javax.swing.JFrame(), true);
          b.setVisible(true);
       }
     tot.setText("Total:  $"+calcular());    
   }
   public float calcular(){
       total=0;
     for(int x=0;x<tabla.getRowCount();x++)
         total+=(float)tabla.getValueAt(x, 6);
     return total;
   }
   public boolean serepite(String s){
      for(int x=0;x<codigos.size();x++)
         if(s.equals(codigos.get(x)))return true;
     return false; 
   }
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       this.dispose();
        Cliente c= new Cliente(new javax.swing.JFrame(),true);        // TODO add your handling code here:
       c.setVisible(true);
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        Proveedor p= new Proveedor(new javax.swing.JFrame(),true);
        p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Recarga p= new Recarga(new javax.swing.JFrame(),true);
        p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Producto p= new Producto(new javax.swing.JFrame(),true);
        p.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarFocusGained
        // TODO add your handling code here:
        if(buscar.getText().equals("Escanea o inserta código")){
            buscar.setText("");
            buscar.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_buscarFocusGained

    private void buscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarFocusLost
        // TODO add your handling code here:
        if(buscar.getText().equals("")) buscar.setText("Escanea o inserta código");
    }//GEN-LAST:event_buscarFocusLost

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
      if(!isDigit(evt.getKeyChar()) || buscar.getText().length()>15) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(activar) {
            tabla.getColumnModel().getColumn(0).setMaxWidth(30);
            tabla.getColumnModel().getColumn(0).setMinWidth(30);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
            activar = false;
            cod.setLocation(cod.getX()+30, cod.getY());
            prod.setLocation(prod.getX()+30, prod.getY());
            marc.setLocation(marc.getX()+15, marc.getY());
            prec.setLocation(prec.getX()+15, prec.getY());
            cantidad.setLocation(cantidad.getX()+30, cantidad.getY());
            importe.setLocation(importe.getX()+15, importe.getY());

        }
        else {
                int cont=0;
                DefaultTableModel mm = (DefaultTableModel) tabla.getModel();
                int fils = mm.getRowCount();
                ArrayList<Integer> seleccionados= new ArrayList<Integer>();
                cont=0;
                for (int i = 0; i < fils; i++) 
                    if(mm.getValueAt(i, 0).toString().equals("true"))
                    {seleccionados.add(i-cont);
                    precios.remove(i-cont);
                    codigos.remove(i-cont);
                    cont+=1;
                    }
               for (int x=0;x<seleccionados.size();x++)
                    mm.removeRow(seleccionados.get(x));
                
            
//                if(cont!=0)
//                {
//                    activar = true;
                    tabla.getColumnModel().getColumn(0).setMaxWidth(0);
                    tabla.getColumnModel().getColumn(0).setMinWidth(0);
                    tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
//                    
//                    
//                 } 
//                else 
//                {
//                    activar = true;
//                    tabla.getColumnModel().getColumn(0).setMaxWidth(0);
//                    tabla.getColumnModel().getColumn(0).setMinWidth(0);
//                    tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
//
//                }
                activar=true;
            cod.setLocation(cod.getX()-30, cod.getY());
            prod.setLocation(prod.getX()-30, prod.getY());
            marc.setLocation(marc.getX()-15, marc.getY());
            prec.setLocation(prec.getX()-15, prec.getY());
            cantidad.setLocation(cantidad.getX()-30, cantidad.getY());
            importe.setLocation(importe.getX()-15, importe.getY());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyTyped
        // TODO add your handling code here:
        if(precio.getText().length()>3)evt.consume();
    }//GEN-LAST:event_precioKeyTyped

    private void precioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyReleased
        // TODO add your handling code here:
        try{
        if(!isDigit(evt.getKeyChar()))evt.consume();
            float f=Float.parseFloat(precio.getText());
        if(!precio.getText().equals("") && !tot.getText().equals("Total  :$"))
            {if(f>total)
               { aceptar.setEnabled(true);
                cambio.setText("Cambio:$"+(f-total));}
             else 
                {aceptar.setEnabled(false);
                 cambio.setText("Cambio:$");}
            }
        }catch(Exception e){}
    }//GEN-LAST:event_precioKeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
           AdvertenciaC c= new AdvertenciaC(new javax.swing.JFrame(), true,this);
        c.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel3MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                venta dialog = new venta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel cambio;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cod;
    private javax.swing.JLabel importe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel marc;
    private javax.swing.JLabel prec;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel prod;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
int x,y;
}
